# Generated by Django 2.0.5 on 2018-07-10 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifedata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('discipline', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='YES', max_length=3)),
            ],
        ),
    ]
